Webb/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webb.Interfaces;

namespace Webb.Models
{
    public class Movie : IMovieModelInterface
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime ReleasedDate { get; set; }
        public string Genre { get; set; }
        public int VotesInGeneral { get; set; }
        public bool? IsPositive { get; set; }
        public int PositiveVotes { get; set; }
    }
}

Webb/Controllers/CreditCardsController.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Webb.Interfaces;
using Webb.Models;

namespace Webb.Controllers
{
    public class CreditCardsController : Controller
    {
        private string DeleteCreditCardApi = "https://localhost:44302/api/DeleteCreditCard";

        public IActionResult DeleteCreditCard(ICreditCardModelInterface creditCard)
        {
            var client = new WebClient();
            client.Headers[HttpRequestHeader.ContentType] = "application/json";
            client.UploadString(DeleteCreditCardApi, JsonConvert.SerializeObject(creditCard));
            return View("Billing", "Home");
        }
    }
}

Webb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Webb.Interfaces;
using Webb.Models;
using Webb.ViewModels;

namespace Webb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            if (String.IsNullOrWhiteSpace(Request.Cookies["token"]))
                return View();
            return View("IndexLogged");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });

        public IActionResult Submit(IUserModelInterface user)
        {
            if (user == null)
                return RedirectToAction("Index", "Home");
            Response.Cookies.Append("token", ClassAPI.UserLogin(user));

            return RedirectToAction("Movies");
        }

        [TokenAuthorizeAttributeRedirect]
        public IActionResult Login() => View();

        [TokenAuthorize]
        public IActionResult Movies()
        {
            var user = Int32.TryParse(Request.Cookies["token"], out int result);
            if (result == 0 || bool.Parse(ClassAPI.CheckUser(result)) == false)
                return RedirectToAction("Billing","Home");

            return View(ClassAPI.MovieViewModel());
        }

        public IActionResult Related(string genre)
        {
            if (genre == null || String.IsNullOrWhiteSpace(genre))
                return RedirectToAction("Movies", "Home");

            return View("Movies", new MoviesViewModel() { Movies = ClassAPI.ReturnMovies(), Genres = new List<GenreDto>() { new GenreDto() { GenreName = genre } } });
        }

        [TokenAuthorizeAttributeRedirect]
        public IActionResult Register() => View();

        public IActionResult RegisterNewUser(IUserModelInterface user)
        {
            if (!ModelState.IsValid)
                return View("Register");

            var token = ClassAPI.RegisterUser(user);
            if (String.IsNullOrWhiteSpace(token))
                return View("Register");
            Response.Cookies.Append("token", token);

            return View("IndexLogged");
        }

        [TokenAuthorize]
        public IActionResult Billing() => View(ClassAPI.UserCreditCards(Request.Cookies["token"]));

        public IActionResult CreditCard(CreditCard creditCard)
        {
            creditCard.UserId = Convert.ToInt32(Request.Cookies["token"]);

            if (!ModelState.IsValid)
                return RedirectToAction("Billing");
            else
                ClassAPI.AddCreditCard(creditCard);

            return RedirectToAction("Billing");
        }

        [TokenAuthorize]
        public IActionResult LogOut()
        {
            Response.Cookies.Delete("token");
            return View("Index");
        }

        [TokenAuthorize]
        public IActionResult Player(IMovieModelInterface movie)
        {
            if (movie.Name == null)
                movie.Name = ClassAPI.ReturnMovies().ToList().Where(c => c.Id == movie.Id).First().Name;

            try
            {
                var result = ClassAPI.ReturnVoting(movie.Id);

                if(result != null)
                {
                    var vote = result.Where(c => c.UserId == Int32.Parse(Request.Cookies["token"])).Single();
                    if (vote != null)
                        movie.IsPositive = vote.IsPositive;

                    movie.VotesInGeneral = result.Count();
                    movie.PositiveVotes = result.Where(c => c.IsPositive == true).Count();
                }
            }
                
            catch (Exception)
            {
                return View(movie);
            }
                
            return View(movie);
        }
    }
}

Webb/Views/Home/Billing.cshtml
@model Webb.ViewModels.UserCreditCards
@{
    ViewData["Title"] = "Billing";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}

<h1>Billing</h1>
@if (Model.CreditCards.ToList().Count() > 0)
{
    <h3>My cards:</h3>
    <table class="table table-striped">
        <tr>
            <th>Card number</th>
            <th>Card owner</th>
            <th>Expiry date</th>
            <th>Paid</th>
            <th>Remove</th>
        </tr>
        @foreach (var creditCard in Model.CreditCards)
        {
            <tr>
                <td>@creditCard.CardNumber</td>
                <td>@creditCard.CardOwner</td>
                <td>@creditCard.ExpiryDate.ToString("MM/yyyy")</td>
                <td>Paid</td>
                <td>@Html.ActionLink("Remove", "DeleteCreditCard", "CreditCards", creditCard)</td>
            </tr>
        }
    </table>
}
else
{
    <h3>You have no saved cards.</h3>
}
<div style="width: 40%; margin: auto">
    @using (Html.BeginForm("CreditCard", "Home"))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.CreditCard.CardNumber)
            @Html.TextBoxFor(m => m.CreditCard.CardNumber, null, new { @class = "form-control", placeholder = "0000 0000 0000 0000", type="number" })
            @Html.ValidationMessageFor(m => m.CreditCard.CardNumber)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CreditCard.CardOwner)
            @Html.TextBoxFor(m => m.CreditCard.CardOwner, null, new { @class = "form-control", placeholder = "Card Owner" })
            @Html.ValidationMessageFor(m => m.CreditCard.CardOwner)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CreditCard.ExpiryDate)
            @Html.TextBoxFor(m => m.CreditCard.ExpiryDate, null, new { @class = "form-control", placeholder = "MM / YYYY" })
            @Html.ValidationMessageFor(m => m.CreditCard.ExpiryDate)
            <br />
            @Html.LabelFor(m => m.CreditCard.CvvNumber)
            @Html.TextBoxFor(m => m.CreditCard.CvvNumber, null, new { @class = "form-control", placeholder = "CVV", type="number", min="1" })
            @Html.ValidationMessageFor(m => m.CreditCard.CvvNumber)
        </div>

        <button type="submit" class="btn btn-primary">
            Save
        </button>
    }
</div>

Webb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4" style="font-size: 120px">MyFlix Project</h1>
    @Html.ActionLink("Register", "Register", "Home", null, new { @class = "btn btn-primary" })
</div>

Webb/Views/Home/IndexLogged.cshtml
@model Webb.Models.User
@{
    ViewData["Title"] = "IndexLogged";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}

Webb/Views/Home/Login.cshtml
@model Webb.Models.User
@{
    ViewData["Title"] = "Home Page";
}
<h1>Login</h1>
@using (Html.BeginForm("Submit", "Home"))
{
<div class="form-group">
    @Html.LabelFor(m => m.Username)
    @Html.TextBoxFor(m => m.Username, null, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Username)
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Password)
    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Password)
</div>
    <input type="submit" value="Login" class="btn btn-primary" />
}

Are you new user? 
@Html.ActionLink("Register", "Register", "Home", null, new { @class = "btn btn-primary"})

Webb/Views/Home/Movies.cshtml
@model Webb.ViewModels.MoviesViewModel
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_LayoutLogged.cshtml";
}

<h1>MyFlix Movies</h1>
<div class="text-center">
    <div style="text-align: left; font-size: 24px;"></div>
    @foreach (var genre in Model.Genres)
    {
        <div style="text-align: left; font-size: 24px; border-radius: 2px">@genre.GenreName</div>
        <ul class="movie-group">
            @foreach (var movie in Model.Movies.Where(m => m.GenreName == genre.GenreName))
            {
                <li style="border: 2px solid #007bff">
                    @Html.ActionLink(movie.Name, "Player", movie)<br />
                    <i class="material-icons movie-icon" style="color: black !important">
                        movie
                    </i>
                </li>
            }
        </ul>
        <div style="clear:both"></div>
    }
</div>

Webb/Views/Home/Player.cshtml
@model Webb.Models.MovieDto
@{
    ViewData["Title"] = "Player";
    Layout = "~/Views/Shared/_LayoutPlayer.cshtml";
    string poster = Model.Id + ".jpg";
}
<div class="movie-details">
    <div id="poster">
        <img src="~/Posters/@poster" style="height:300px; width:202px"/>
    </div>
    <div class="details">
        <table class="table table-striped" style="min-width: 400px">
            <tr>
                <td><h2>@Model.Name</h2></td>
            </tr>
            <tr>
                <td>Genre: @Model.GenreName - @Html.ActionLink("Look for related movies!", "Related", "Home", new { genre = Model.GenreName}, new { @style = "color: #2AB3D2" })</td>
            </tr>
            <tr>
                <td>Release Date: @Model.ReleasedDate.ToString(" dd MMMM yyyy")</td>
            </tr>
        </table>
    </div>
    <div class="details">
        <div id="voting">
            <a href="@Url.Action("Vote", "Movies", new Webb.ViewModels.VotedViewModel { IsPositive = "True", MovieId = Model.Id, UserId = Model.UserId })" style="color: #AAAAAA">
                <i class="material-icons thumb_up" id="thumbUp">thumb_up</i>
            </a>
            <a href="@Url.Action("Vote","Movies", new Webb.ViewModels.VotedViewModel { IsPositive = "False", MovieId = Model.Id, UserId = Model.UserId })" style="color: #AAAAAA">
                <i class="material-icons thumb_down" id="thumbDown">thumb_down</i>
            </a>
            <div id="results"></div>
        </div>
    </div>
</div>
<div style="clear: both"></div>
<div style="background-color: #1B2127">

    <video id="my-video"
           class="video-js"
           controls
           preload="auto"
           width="896"
           height="370"
           poster="https://whatsondisneyplus.com/wp-content/uploads/2019/11/20th-century-fox-logo.jpg"
           data-setup="{}"
           style="margin: auto">
        <source src="~/Videos/sample.mp4" type="video/mp4" />
        <source src="http://techslides.com/demos/sample-videos/small.webm" type="video/webm" />
        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a
            web browser that
            <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
    </video>
    <script src="https://vjs.zencdn.net/7.5.5/video.js"></script>
</div>

@section scripts {
    <script>
        $(document).ready(function () {
            var colourUp = @Model.IsPositive.ToString().ToLower();
            if (colourUp == true) {
                var thumb = document.getElementById("thumbUp");
                thumb.style.color = "green";
            }
            else if (colourUp == false) {
                var thumb = document.getElementById("thumbDown");
                thumb.style.color = "red";
            }
        })
        $(document).ready(function () {
            var positiveVotes = @Model.PositiveVotes;
            var votesInGeneral = @Model.VotesInGeneral;

            document.getElementById("results").innerText = "Positive in: " + (positiveVotes / votesInGeneral) * 100 + "% (" + votesInGeneral + " votes in general)";
        })
    </script>
}

Webb/Views/Home/Register.cshtml
@model Webb.Models.User
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Register</h1>

@using (Html.BeginForm("RegisterNewUser", "Home"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Username)
        @Html.TextBoxFor(m => m.Username, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Username)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password)
        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Password)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Birthdate)
        @Html.TextBoxFor(m => m.Birthdate, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Birthdate)
    </div>
    <button type="submit" class="btn btn-primary">
        Register
    </button>
}